from dotenv import load_dotenv
from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated, List
import operator
from langgraph.checkpoint.sqlite import SqliteSaver
from langchain_core.messages import AnyMessage, SystemMessage, HumanMessage, AIMessage, ChatMessage

# Load environment variables (e.g., API keys)
load_dotenv()

# Define the state schema
class AgentState(TypedDict):
    task: str # Human Input (e.g., "Write an essay about the importance of AI in education.")
    plan: str # Plan generate by the agent (e.g., "1. Research the topic. 2. Create an outline. 3. Write the essay.")
    draft: str # Draft of the essay generated by the agent (e.g., "Artificial Intelligence (AI) has become a transformative force in education...")
    critique: str # Critique of the draft generated by the agent (e.g., "The essay is well-structured, but it could benefit from more specific examples and references to recent studies.")
    content: List[str] # List of documents that the Tavily agent has read/researched and used to generate the essay (e.g., ["Document 1: AI in Education - A Comprehensive Review", "Document 2: The Impact of AI on Learning Outcomes"])
    revision_number: int # The number of revisions the agent has made to the essay (e.g., 1, 2, 3, etc.)
    max_revisions: int # The maximum number of revisions the agent is allowed to make to the essay (e.g., 3, 5, etc.)

# Initialize the SQLite saver for agent memory
memory = SqliteSaver("agent_memory.db")

print("Environment and imports are set up successfully! Ready to build the Essay Writer.")
